version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: crud_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  
  api-service:
    build: ./api-service
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: crud_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - postgres-db
  
  nginx-gateway:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - api-service
